### ISSUE TITLE
[Seren 2.0.9] Scene name missing

### ISSUE THREAD

**Issue by DaisyF8** [drinfernoo/seren.theme.ah#5]
Sometimes for TV I get only Showname and episode in the textfield where the stream-name goes. I then miss the name of the release group.

**Comment by DaisyF8** [comment]
Using another skin, haven't been checking this issue anymore

Closed

**Comment by vermope** [comment]
I'm still having this issue.... would be nice to see it back.

**Comment by drinfernoo** [comment]
This is a actually due to #12, which should hopefully be fixable in Seren itself.

**Comment by vermope** [comment]
Ok, thanks for clarifying!
