### ISSUE TITLE
[BUG] Can't scroll down after moving up to Re-Scrape & Trakt Manager options

### ISSUE THREAD

**Issue by Nuklear92** [drinfernoo/seren.theme.ah#6]
As the title says, once you're within the source select screen, once you move up to click/check either **Rescrape**, **Trakt Manager** options you cannot go down to select a link/source. The only way is to click back button on the remote to return back to title list and click to scrape again.

**Comment by drinfernoo** [comment]
I'm thinking I just need to look at the `<ondown>` value in those buttons, maybe something's gotten goofed up in a Seren update.

**Comment by Nuklear92** [comment]
@drinfernoo Not fixed with 0.0.7

**Comment by Nuklear92** [comment]
Fixed in 0.0.8, thanks!
